import fs from 'node:fs';
import path from 'node:path';
import type { Architecture } from './types';

/* The viewer is the original standalone engine, kept verbatim in /viewer.
 * The studio never re-implements rendering: what you preview in an iframe is
 * byte-for-byte what you download and what you would host. One renderer, one
 * behaviour, no drift. */

const VIEWER_DIR = path.join(process.cwd(), 'viewer');

let cache: { css: string; js: string; mtime: number } | null = null;

function viewerAssets() {
  const cssPath = path.join(VIEWER_DIR, 'style.css');
  const jsPath = path.join(VIEWER_DIR, 'engine.js');
  const mtime = Math.max(fs.statSync(cssPath).mtimeMs, fs.statSync(jsPath).mtimeMs);
  if (!cache || cache.mtime !== mtime) {
    cache = {
      css: fs.readFileSync(cssPath, 'utf8'),
      js: fs.readFileSync(jsPath, 'utf8'),
      mtime
    };
  }
  return cache;
}

/** `</script>` inside the JSON payload would close the tag early. */
const safeJson = (doc: Architecture) =>
  JSON.stringify(doc, null, 2).replace(/<\/(script)/gi, '<\\/$1');

export function buildStandaloneHtml(doc: Architecture): string {
  const { css, js } = viewerAssets();
  const lang = doc.meta?.lang === 'fr' ? 'fr' : 'en';
  const theme = doc.ui?.defaultTheme === 'dark' ? 'dark' : 'light';
  const title = [doc.meta?.name, doc.meta?.tagline || 'Architecture Explorer']
    .filter(Boolean).join(' — ');

  return `<!DOCTYPE html>
<html lang="${lang}" data-theme="${theme}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${escapeHtml(title)}</title>
<meta name="generator" content="Architecture Studio">
<link rel="icon" href="data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24'><text y='19' font-size='20'>◆</text></svg>">
<style>
${css}
</style>
</head>
<body>

<header>
  <div class="hwrap">
    <div class="brand">
      <div class="logo" id="logo"></div>
      <div><b id="brandName">…</b><span id="brandSub"></span></div>
    </div>
    <div class="spacer"></div>
    <div class="search">
      <svg viewBox="0 0 24 24"><circle cx="11" cy="11" r="7"/><path d="m20 20-3.5-3.5"/></svg>
      <input id="q" type="search" autocomplete="off">
    </div>
    <button class="iconbtn" id="themeBtn" aria-label="Theme">
      <svg id="themeIcon" viewBox="0 0 24 24"><path d="M21 12.8A9 9 0 1 1 11.2 3a7 7 0 0 0 9.8 9.8z"/></svg>
    </button>
    <button class="iconbtn" id="printBtn" aria-label="Print">
      <svg viewBox="0 0 24 24"><path d="M6 9V3h12v6"/><rect x="3" y="9" width="18" height="8" rx="2"/><path d="M6 15h12v6H6z"/></svg>
    </button>
  </div>
  <nav class="tabs" id="tabs" role="tablist"></nav>
</header>

<main id="main"></main>

<div class="scrim" id="scrim"></div>
<aside class="drawer" id="drawer" role="dialog" aria-modal="true">
  <div class="dh" id="dh"></div>
  <div class="db" id="db"></div>
</aside>

<script>
window.ARCHITECTURE = ${safeJson(doc)};
</script>
<script>
${js}
</script>
</body>
</html>
`;
}

/** The same document as a drop-in data file for the standalone viewer repo. */
export function buildDataFile(doc: Architecture): string {
  return `/* Generated by Architecture Studio — ${new Date().toISOString().slice(0, 10)} */\n\n`
    + `window.ARCHITECTURE = ${safeJson(doc)};\n`;
}

function escapeHtml(s: string) {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

export function safeFilename(name: string, ext: string) {
  const base = (name || 'architecture')
    .normalize('NFD').replace(/[̀-ͯ]/g, '')
    .replace(/[^a-zA-Z0-9-_ ]/g, '').trim().replace(/\s+/g, '-').toLowerCase() || 'architecture';
  return `${base}.${ext}`;
}
